## 使用NumPy进行数据计算

In [2]:
import numpy as np

#### 作业题目中需要用到的数组

In [3]:
np.random.seed(1)
a1 = np.arange(10)
a2 = np.array([1,5,7,4,3])
a3 = np.arange(20).reshape(4,-1)
a4 = np.random.uniform(10,20,50)
a5 = np.random.randint(0,5,10)
a6 = np.array([1, 3, 7, 1, 2, 6, 0, 1])
a7 = np.random.randint(1,4,size = 6)
a8 = np.random.randint(20,size = [2,6])
b1 = np.arange(10).reshape(2,-1)
b2 = np.repeat(1,10).reshape(2,-1)
b3 = np.array(
[np.arange(3),
np.arange(3,6),
np.arange(6,9)])
b4 = np.array([1,2,3,4])
b5 = np.array([5,6,7,8])

#### 例题以及答案格式

In [4]:
# Q.创建一个3×3的所有值为True的numpy数组
# A:
out = np.ones((3,3),dtype = bool)
out   #运行之后可以直接看到结果

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

#### 作业共25道，Q为题目序号，A为答案序号，请阅读题目后在A下作答，不要删除题目中的np.random.seed

##### Q1.将a1转换为2行的2维数组 *注：答案中只明确是2行，系统自动确定列数(★☆☆)

In [4]:
# A1:
arr = a1.reshape(2,-1)
arr

array([[0, 1, 2, 3, 4],
       [5, 6, 7, 8, 9]])

##### Q2.创建一个10*10的随机数组，并找到这个数组中的最大值、最小值和平均值(★☆☆)

In [5]:
# A2:
arr_random = np.random.randint(0,100,size = [10,10])
# 找到最大值
a=arr_random.max()
# 找到最小值
b=arr_random.min()
# 找到平均值
c=arr_random.mean()
print(a,b,c)

98 0 50.67


##### Q3.创建一个随机5*5矩阵并对它进行归一化（减去平均值再除以方差）(★☆☆)

In [6]:
#A3：
arr_random = np.random.randint(0,100,size = [5,5])
# 找到平均值
a=arr_random.mean()
# 找到方差
b=arr_random.var()
# 归一化
c=(arr_random-a)/b
print(c)

[[ 0.02589964 -0.02269255 -0.00082607  0.04776612 -0.02512216]
 [-0.06278111  0.03683288  0.03561807 -0.00690009  0.00038874]
 [-0.02633697 -0.03119618  0.00160354  0.03440327 -0.02755177]
 [-0.03119618  0.04898092  0.02468483 -0.05549228  0.05505495]
 [-0.02633697 -0.05549228  0.03683288  0.02832925 -0.00447048]]


##### Q4.删除a1中所包含的a2的元素(★☆☆)

In [7]:
# A4：
arr = np.delete(a1,a2)
arr

array([0, 2, 6, 8, 9])

##### Q5.提取a1中的所有奇数为新的数组，并使得a1不发生改变(★☆☆)

In [8]:
# A5:
arr = a1[a1%2==1]
arr

array([1, 3, 5, 7, 9])

##### Q6.交换数组a3中的第一行和第3行，第二列和最后一列(★☆☆)

In [9]:
# A6：
arr = a3.copy()
arr[[0,2],:] = arr[[2,0],:]
arr[:,[1,-1]] = arr[:,[-1,1]]
arr

array([[10, 14, 12, 13, 11],
       [ 5,  9,  7,  8,  6],
       [ 0,  4,  2,  3,  1],
       [15, 19, 17, 18, 16]])

##### Q7.(1)反转a3的行 （2）反转a3的列(★☆☆)

In [10]:
# A7：
arr1 = a3.copy()
arr1 = arr[::-1,:]
arr1
arr2 = a3.copy()
arr2 = arr[:,::-1]
arr2

array([[11, 13, 12, 14, 10],
       [ 6,  8,  7,  9,  5],
       [ 1,  3,  2,  4,  0],
       [16, 18, 17, 19, 15]])

##### Q8.在b1的周围加一个全部为0的边框(★★☆)

In [11]:
# A8：
arr = np.pad(b1,1,'constant',constant_values = 0)
arr

array([[0, 0, 0, 0, 0, 0, 0],
       [0, 0, 1, 2, 3, 4, 0],
       [0, 5, 6, 7, 8, 9, 0],
       [0, 0, 0, 0, 0, 0, 0]])

##### Q9.创建一个5*5的矩阵，值“1，2，3，4”在此矩阵对角线的正上方(★★☆)

In [12]:
# A9：
arr = np.diag(1+np.arange(4),k = -1)
arr

array([[0, 0, 0, 0, 0],
       [1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0]])

##### Q10.从数组a3中提取7到16之间的所有元素，包括7和16(★★☆)

In [13]:
# A10:
arr = a3[(a3>=7)&(a3<=16)]
arr

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15, 16])

##### Q11.创建一个4*6的二维数组，包含10~20之间的浮点数，并保留三位小数(★★☆)

In [14]:
#A11：
arr = np.random.uniform(10,20,size = [4,6])
arr = np.round(arr,3) #保留三位小数
arr

array([[10.36 , 16.543, 11.298, 12.944, 13.608, 12.746],
       [10.74 , 11.521, 11.616, 19.387, 13.711, 10.5  ],
       [17.41 , 12.987, 12.044, 19.818, 18.93 , 17.593],
       [16.511, 10.397, 18.139, 17.626, 14.553, 15.318]])

##### Q12.将b3转换为一维数组(★★☆)

In [15]:
# A12：
arr = b3.flatten()
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8])

##### Q13.获取a4中前五个最大的值(★★☆)

In [16]:
# A13：
arr = np.sort(a4)[-5:]
arr

array([18.94606664, 19.08595503, 19.5788953 , 19.68261576, 19.88861089])

##### Q14.计算b4和b5之间的欧式距离(★★☆)

In [17]:
# A14:
arr = np.linalg.norm(b4-b5)
# 输出距离
arr

8.0

##### Q15:找出a5中重复的元素并标记为True（如果元素第一次出现则标记为False） (★★★)

In [18]:
a5

array([1, 3, 0, 0, 2, 2, 1, 3, 4, 2])

In [19]:
# A15：
arr = np.full(a5.shape,False)
arr

array([False, False, False, False, False, False, False, False, False,
       False])

##### Q16:给出下列A和B，求解2Ax = B(★★★)

In [20]:
A = np.array([[1,2,3],[-1,-3,-9],[2,2,8]])
B = np.array([12,15,8])
# A16：
arr = np.linalg.solve(2*A,B)
arr

array([10.5,  1.5, -2.5])

##### Q17:筛选iris_2d中同时满足行petallength (3rd column) > 1.5sepallength (1st column) < 5.0的项目

In [21]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
iris_2d = np.genfromtxt(url, delimiter=',', dtype='float', usecols=[0,1,2,3])
#A17：
arr = iris_2d[(iris_2d[:,2]>1.5)&(iris_2d[:,0]<5.0)]
arr

array([[4.8, 3.4, 1.6, 0.2],
       [4.8, 3.4, 1.9, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [4.9, 2.4, 3.3, 1. ],
       [4.9, 2.5, 4.5, 1.7]])

##### Q18:对数组a8中各项目进行排名，数值越小排名越高，如果存在并列情况，在a8中位置越靠前则排名越高。
##### 例：[1,3,4,5,4,1]——————排名为：[0,2,3,5,4,1]

In [22]:
# A18:
arr = np.argsort(a8)
arr

array([[2, 1, 4, 5, 0, 3],
       [0, 3, 5, 2, 1, 4]], dtype=int64)

##### Q19:以iris species作为输入，创建不同类别的ID.
##### 如令所有的'Iris-setosa'都为0,所有的'Iris-versicolor'都为1(★★★)

In [23]:
url = 'https://archive.ics.uci.edu/ml/machine-learning-databases/iris/iris.data'
species = np.genfromtxt(url,delimiter = ',',dtype = 'str',usecols = 4)
# A19：
arr = np.unique(species,return_inverse = True)
arr

(array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15'),
 array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
        2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2], dtype=int64))

##### Q20:创建一个3*10的numpy数组Z
##### 请回答print函数中的代码的功能(★★★)

In [105]:
Z = np.random.randint(0,3,(3,10)) 

In [106]:
Z

array([[2, 2, 0, 1, 2, 1, 1, 1, 1, 0],
       [1, 2, 1, 0, 0, 2, 2, 1, 0, 0],
       [0, 2, 2, 0, 1, 1, 1, 2, 1, 1]])

In [111]:
(~Z.any(axis=0)).any()

False

In [112]:
~Z.any(axis=0)

array([False, False, False, False, False, False, False, False, False,
       False])

In [102]:
print((~Z.any(axis=0)).any())

False


In [ ]:
# A20：
# 判断Z中是否存在全为0的列